rule:
  place_size_rule: true
  break_size_rule: true

location:
  lobby:
    x:
    y:
    z:
  build_spawn:
    x:
    y:
    z:
  build_arena:
    start:
      x:
      y:
      z:
    end:
      x:
      y:
      z: